### ISSUE TITLE
Implement Call and Refer in FAB

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#15]
This button should be the same as the FAB in the client's profile page:

- [x] If a family member or child U5, similar to [CHW #248](https://github.com/OpenSRP/opensrp-client-chw/issues/248) but with "Refer to facility", similar to [CHW #269](https://github.com/OpenSRP/opensrp-client-chw/issues/269)
- [x] If an ANC client, similar as([ANC #34](https://github.com/OpenSRP/opensrp-client-chw-anc/issues/34)) but with "Refer to facility", similar to [CHW #269](https://github.com/OpenSRP/opensrp-client-chw/issues/269)
- [x] If PNC client, similar as (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/80) but with "Refer to facility", similar to [CHW #269](https://github.com/OpenSRP/opensrp-client-chw/issues/269)

**Comment by whoisladleo** [comment]
If they are in multiple registers
Say ANC - it will say ANC client
If they are in one register is will say Malaria client
If they are head of household it will say the head of family

So the hierarchy is:
1. Head of family
2. .ANC,
3. Caregiver,
4.  PNC
5. Malaria client

**Comment by whoisladleo** [comment]
@manutarus we need to populate the family head details.

**Comment by msschroeder** [comment]
lgtm
