### ISSUE TITLE
Implement malaria profile page with more than one visit required

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#22]
When a client only has a malaria follow up visit, the client profile page will appear as below.

<img width="254" alt="Screen Shot 2019-05-09 at 10 05 37 PM" src="https://user-images.githubusercontent.com/20777928/57480776-4ee23d80-72a9-11e9-82aa-cda68a535c49.png">

- [x] Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the malaria register list, the label should be "Return to all malaria clients"
- [x] Top right 3 dots menu opens menu of options ( #19 )
- [x] Avatar or image of the client if taken in registration form
- [x] The profile information like the name, age, location and ID is taken as is from the ANC profile page if in ANC register ([ANC #10](https://github.com/OpenSRP/opensrp-client-chw-anc/issues/10)), taken from PNC profile page if in PNC register (not yet implemented), taken from child U5 if in Child register ([child #43](https://github.com/OpenSRP/opensrp-client-chw/issues/43))
- [x] Record malaria follow-up visit button row ( #20  )
- [x] Medical history row ( #41  )
- [x] Upcoming services row ( #10 )
- [ ] Malaria positive [date] row (#39)
- [x] Family has services due/overdue row (already implemented)
- [x] Call FAB ( #15  )

**Comment by whoisladleo** [comment]
#39 is being done by @JafariUCC
