### ISSUE TITLE
Add follow-up visit form

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#7]
- [x] The follow-up visit form is accessible from the Malaria profile top right menu. It should appear between "Registration Info" and "Remove this person" (#19 )
- [x] Title of form "Follow-up Visit"
- [x] If {fever_still} = "Yes", the record will remain in the malaria. Ideally, upon submitting the form, the Malaria referral form will open. If not possible, upon submitting the form, the CHW will access the referral form from the FBA button "Refer to Facility" will be acceptable too.
- [x]  If {fever_still} = "No": The record will be removed from the malaria register (#23 )
- [x] The form can be displayed on all one page.
- [x] Follow the exact content from the [data dictionary](https://docs.google.com/spreadsheets/d/1udEAH5_WR5BiRUhKOSIuurny4VxItQ0kjHw9zSaaKDk/edit?usp=sharing), CHW 2 - Follow-up visit tab, for this form.
- [x] Follow a style similar to the image below

<img width="254" alt="Screen_Shot_2019-05-09_at_9_57_24_PM" src="https://user-images.githubusercontent.com/20777928/57479228-9e266f00-72a5-11e9-9107-1c1d908f27e5.png">

- [x] "Submit" will submit the form
- [x] "X" will result in a "Confirm form close" asking, "Are you sure you want to go back? All data you have entered in this form will be cleared" 
- [x] If select "No" in the "Confirm form close", it will return to the filled form. 
- [x] If you select "Yes" in the "Confirm form close", it will close the form and all data entered will be lost.

**Comment by msschroeder** [comment]
QA Sept 21:
- [x] Include the `fever_referal` in the form when {fever_still} = "Yes" as noted in the data dictionary (highlighted in pink)
- [x] "Submit" will submit the form - This is not currently happening. When you submit, another follow up form appears
- [ ] If {fever_still} = "Yes", the record will remain in the malaria. Ideally, upon submitting the form, the Malaria referral form will open. If not possible, upon submitting the form, the CHW will access the referral form from the FBA button "Refer to Facility" will be acceptable too. - This is currently not happening
- [x]  If {fever_still} = "No": The record will be removed from the malaria register (#23 ) - This is currently not happening

To replicate:
1. Open a follow-up visit form
2. Fill in
3. Submit - Nothing happens

**Comment by msschroeder** [comment]
QA November 18:
- [ ] If {fever_still} = "Yes", the record will remain in the malaria. The follow-up visit task should no longer appear. The CHW would make a referral. If the referral is not made in the {malaria_test_date} + 14 days, the record would be archived. However, the task of a follow-up visit still remains and shows as if the follow-visit form was never filled.

**Comment by manutarus** [comment]
@msschroeder if the CHW does make a referral within 14 days, what happens to the record?

**Comment by msschroeder** [comment]
QA March 18:
- [ ] If you fill in the follow up visit, the task should disappear. Right now, you can continue to fill the follow-up visit task as many times as you want
