### ISSUE TITLE
Implement malaria profile page with only malaria visit

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-malaria#8]
When a client only has a malaria follow up visit, the client profile page will appear as below.
<img width="248" alt="Screen_Shot_2019-05-09_at_10_08_51_PM" src="https://user-images.githubusercontent.com/20777928/57479938-32dd9c80-72a7-11e9-9f16-c85aac3eb9d0.png">

- [x] Back arrow or device back button takes user to the previous page they were viewing. If coming from the family profile page, the label should be "Return to family members"; if coming from the malaria register list, the label should be "Return to all malaria clients"
- [x] Top right 3 dots menu opens menu of options ( #19  )
- [x] Avatar or image of the client if taken in registration form
- [x] The profile information like the name, age, location and ID is taken as is from the family registration profile or from their respective profiles: child, ANC, PNC
- [x] Record malaria follow-up visit button row ( #20  )
- [x] Medical history row ( #41  )
- [ ] Upcoming services row ( #33  )
- [ ] Malaria positive [date] row (#39) - shown below

<img width="306" alt="Screen Shot 2019-06-18 at 11 21 18 AM" src="https://user-images.githubusercontent.com/20777928/59665261-3d028d00-91bb-11e9-9aac-6355ad8a5d5d.png">

- [x] Family has services due/overdue row (already implemented)
- [x] Call FAB ( #15  )

**Comment by msschroeder** [comment]
@manutarus @ladleo Please not I added another line to the profiles for both issues #22 and this issue to show the malaria confirmation form. I have created an issue to go with it!

**Comment by msschroeder** [comment]
lgtm
